"""Add favorites table and others

Revision ID: 1a44a6aa3874
Revises: eec6730963d0
Create Date: 2024-08-15 00:31:14.102286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a44a6aa3874'
down_revision = 'eec6730963d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
