"""change relations

Revision ID: 714408eebe97
Revises: a89b0c270af7
Create Date: 2024-08-15 01:56:24.180480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714408eebe97'
down_revision = 'a89b0c270af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
