"""Add is_local column to Game model

Revision ID: 8e55d2ac4b28
Revises: 372396ff96df
Create Date: 2024-08-15 02:23:44.938558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e55d2ac4b28'
down_revision = '372396ff96df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
