"""add is local

Revision ID: a89b0c270af7
Revises: 1a44a6aa3874
Create Date: 2024-08-15 01:49:20.138156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89b0c270af7'
down_revision = '1a44a6aa3874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_local', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_local')
    # ### end Alembic commands ###
