"""change relations

Revision ID: ae750d0e8ffa
Revises: 714408eebe97
Create Date: 2024-08-15 02:03:43.947333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae750d0e8ffa'
down_revision = '714408eebe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
