"""Initial migration

Revision ID: c4bc328e3564
Revises: ae750d0e8ffa
Create Date: 2024-08-15 02:19:35.377895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bc328e3564'
down_revision = 'ae750d0e8ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
